/*
 * UART_cfg.h
 *
 *  Created on: Aug 16, 2019
 *      Author: Muhammad.Elzeiny
 */

#ifndef F15_REPO_SRC_CONFIG_UART_CFG_H_
#define F15_REPO_SRC_CONFIG_UART_CFG_H_

#define UART_TX_BUFFER_SIZE				50
#define UART_RX_BUFFER_SIZE				50
#define UART_BAUDE_RATE_UBRR			103
#define UART_DOUBLE_SPEED				DISABLE

#define UART_INTERRUPT_TXC				ENABLE
#define UART_INTERRUPT_RXC				ENABLE
#define UART_INTERRUPT_UDR				DISABLE
/*
 * UART_DATA_SIZE_5
 * UART_DATA_SIZE_6
 * UART_DATA_SIZE_7
 * UART_DATA_SIZE_8
 * UART_DATA_SIZE_9
 * */
#define UART_DATA_SIZE_SELECTOR			UART_DATA_SIZE_8
/*
 * UART_PARITY_MODE_DISABLE
 * UART_PARITY_MODE_EVEN
 * UART_PARITY_MODE_ODD
 * */
#define UART_PARITY_MODE_SELECTOR		UART_PARITY_MODE_DISABLE
/*
 * UART_STOP_BIT_1
 * UART_STOP_BIT_2
 * */
#define UART_STOP_BIT_SELECTOR			UART_STOP_BIT_1

#endif /* F15_REPO_SRC_CONFIG_UART_CFG_H_ */
